//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Wiki_test.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Wiki_testEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Wiki_testEntities object using the connection string found in the 'Wiki_testEntities' section of the application configuration file.
        /// </summary>
        public Wiki_testEntities() : base("name=Wiki_testEntities", "Wiki_testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Wiki_testEntities object.
        /// </summary>
        public Wiki_testEntities(string connectionString) : base(connectionString, "Wiki_testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Wiki_testEntities object.
        /// </summary>
        public Wiki_testEntities(EntityConnection connection) : base(connection, "Wiki_testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<article> article
        {
            get
            {
                if ((_article == null))
                {
                    _article = base.CreateObjectSet<article>("article");
                }
                return _article;
            }
        }
        private ObjectSet<article> _article;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the article EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToarticle(article article)
        {
            base.AddObject("article", article);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Wiki_testModel", Name="article")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class article : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new article object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="title">Initial value of the title property.</param>
        public static article Createarticle(global::System.Int32 id, global::System.String title)
        {
            article article = new article();
            article.id = id;
            article.title = title;
            return article;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String body
        {
            get
            {
                return _body;
            }
            set
            {
                OnbodyChanging(value);
                ReportPropertyChanging("body");
                _body = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("body");
                OnbodyChanged();
            }
        }
        private global::System.String _body;
        partial void OnbodyChanging(global::System.String value);
        partial void OnbodyChanged();

        #endregion
    
    }

    #endregion
    
}
